<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simple_csp" nsURI="http://famosa.github.io/csp/1.0/simple-csp"
    nsPrefix="simple-csp">
  <eClassifiers xsi:type="ecore:EClass" name="Problem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//Domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" eType="#//Domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="BOOLEAN"/>
    <eLiterals name="INTEGER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//NamedElement #//DescribedElement #//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetOp" abstract="true" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exps" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOp" abstract="true" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExp" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExp" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOp" abstract="true" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//UnaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Implies" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equal" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnEqual" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Less" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="LessEqual" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Greater" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterEqual" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Times" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Power" eSuperTypes="#//BinaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sum" eSuperTypes="#//SetOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Min" eSuperTypes="#//SetOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Max" eSuperTypes="#//SetOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarOccurence" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrueValue" eSuperTypes="#//BooleanLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseValue" eSuperTypes="#//BooleanLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaximizeGoal" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinimizeGoal" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
